insert into `legislator` values(1, 'Aquilino Martin', 'de la Llana', 'Pimentel III', str_to_date('01-20-1964', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2022', '%c-%d-%Y'));
insert into `legislator` values(2, 'Paolo Benigno', 'Aguirre', 'Aquino IV', str_to_date('05-07-1977', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(3, 'Miriam Palma', 'Defensor', 'Santiago', str_to_date('06-15-1945', '%c-%d-%Y'), 'F', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(4, 'Loren Regina', 'Bautista', 'Legarda', str_to_date('01-28-1960', '%c-%d-%Y'), 'F', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(5, 'Jose', 'Pimentel', 'Ejercito-Estrada', str_to_date('01-23-1963', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(6, 'Teofisto', 'de Lara', 'Guingona III', str_to_date('04-19-1959', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(7, 'Ramon', '', 'Revilla JR.', str_to_date('09-25-1966', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(8, 'Francis Joseph', 'Guevara', 'Escudero', str_to_date('10-10-1969', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(9, 'Pilar Juliana', 'Schramm', 'Cayetano', str_to_date('03-22-1966', '%c-%d-%Y'), 'F', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(10, 'Juan Edgardo', 'Manalang', 'Angara', str_to_date('07-15-1943', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(11, 'Joseph Victor', 'Gomez', 'Ejercito', str_to_date('12-26-1969', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(12, 'Antonio', 'Fuentes', 'Trillanes', str_to_date('08-06-1971', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(13, 'Mary Grace', 'Llamanzares', 'Poe', str_to_date('01-01-1968', '%c-%d-%Y'), 'F', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(14, 'Maria Lourdes Nancy', 'Sombillo', 'Binay', str_to_date('05-12-1973', '%c-%d-%Y'), 'F', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(15, 'Manuel', 'Mercado', 'Lapid', str_to_date('08-21-1955', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));
insert into `legislator` values(16, 'Ferdinand', 'Romualdez', 'Marcos', str_to_date('09-13-1957', '%c-%d-%Y'), 'M', 'SENATOR', 19550, 3, str_to_date('08-01-2016', '%c-%d-%Y'), str_to_date('08-01-2019', '%c-%d-%Y'));

insert into `bill`
	values(3220, 'TAX AND DUTIES EXEMPTIONS THE PRIZES OF MISS UNIVERSE PIA WURTZBACH',
		'AN ACT EXEMPTING FROM INCOME TAX, VALUE-ADDED TAX, AND IMPORT DUTIES THE WINNINGS AND/OR PRIZES OF MISS PIA ALONZO WURTZBACH AS MISS UNIVERSE 2015, AND FROM DONOR\'S TAX ANY DONATION MADE BY HER FROM SUCH WINNINGS AND/OR PRIZES',
		'SENATE BILL', 'NATIONAL', 'ARCHIVED', null, str_to_date('2016-02-03', '%Y-%c-%d'));
	insert into `bill_author` values(3220, 1);
	insert into `bill_subject` values(3220, 'VALUE-ADDED TAX');
	insert into `bill_subject` values(3220, 'TAX EXEMPTON');

insert into `bill`
	values(3221, 'ORGAN AND TISSUE DONATION ACT OF 2016',
		'AN ACT STRENGTHENING THE HUMAN ORGAN AND TISSUE DONATION AND TRANSPLANTATION PROGRAM AND PROVIDING PENALTIES FOR VIOLATION THEREOF, AMENDING FOR THIS PURPOSE REPUBLIC ACT NO. 7170, AS AMENDED, ALSO KNOWN AS THE ORGAN DONATION ACT OF 1991',
		'SENATE BILL', 'NATIONAL', 'PENDING', '2ND', str_to_date('2016-02-03', '%Y-%c-%d')) ;
	insert into `bill_author` values (3221, 3);
	insert into `bill_author` values(3221, 4);
	insert into `bill_author` values(3221, 5);
	insert into `bill_author` values(3221, 6);
	insert into `bill_subject` values(3221, 'ORGAN DONATION');

insert into `bill`
	values(3222, 'SUMMARY TITLING OF REAL PROPERTIES USED AS PUBLIC SCHOOL SITES',
		'AN ACT PROVIDING FOR THE SUMMARY TITLING OF REAL PROPERTIES USED AS PUBLIC SCHOOL SITES',
		'SENATE BILL', 'NATIONAL', 'COMM REPORT ARCHIVED', NULL, str_to_date('2016-02-03', '%Y-%c-%d'));
	insert into `bill_author` values(3222, 7);
	insert into `bill_author` values(3222, 8);
	insert into `bill_author` values(3222, 9);
	insert into `bill_author` values(3222, 4);
	insert into `bill_author` values(3222, 10);
	insert into `bill_subject` values(3222, 'REAL PROPERTIES');

insert into `bill`
	values(3223, 'PHILIPPINE HIV AND AIDS ACT',
		'AN ACT STRENGTHENING THE PHILIPPINE COMPREHENSIVE POLICY ON HIV AND AIDS PREVENTION, TREATMENT, CARE, AND SUPPORT, REPEALING FOR THE PURPOSE REPUBLIC ACT NO. 8504, OTHERWISE KNOWN AS THE PHILIPPINE AIDS PREVENTION AND CONTROL ACT OF 1998, AND APPROPRIATING FUNDS THEREFORE',
		'SENATE BILL', 'NATIONAL', 'PENDING', '2ND', str_to_date('2016-02-03', '%Y-%c-%d'));
	insert into `bill_author` values(3223, 1);
	insert into `bill_author` values(3223, 2);
	insert into `bill_author` values(3223, 3);
	insert into `bill_author` values(3223, 4);
	insert into `bill_author` values(3223, 5);
	insert into `bill_author` values(3223, 6);
	insert into `bill_author` values(3223, 9);
	insert into `bill_author` values(3223, 11);
	insert into `bill_author` values(3223, 12);
	insert into `bill_author` values(3223, 13);
	insert into `bill_author` values(3223, 14);
	insert into `bill_author` values(3223, 15);

insert into `bill`
	values(3224, "SOLO PARENTS AND THEIR CHILDREN'S WELFARE ACT", 'AN ACT AMENDING REPUBLIC ACT NO. 8972, OTHERWISE KNOWN AS THE SOLO PARENTS WELFARE ACT OF 2000, AND FOR OTHER PURPOSES',
		'SENATE BILL', 'NATIONAL', 'ARCHIVED', null, str_to_date('02-09-2016', '%c-%d-%Y'));
	insert into `bill_author` values(3224, 16);
	insert into `bill_subject` values(3224, "R.A. No. 8972");

insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (17, 'Cory', 'Stockney', 'Charrisson', str_to_date('10/13/1955', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 27416, 2, str_to_date('4/1/2011', '%c/%d/%Y'), str_to_date('8/22/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (18, 'Mariska', 'Carbry', 'Tills', str_to_date('06/21/1957', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 33364, 2, str_to_date('6/7/2014', '%c/%d/%Y'), str_to_date('12/29/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (19, 'Lari', 'Gladden', 'Haworth', str_to_date('09/23/1956', '%c/%d/%Y'), 'F', 'SENATOR', 25672, 2, str_to_date('8/9/2007', '%c/%d/%Y'), str_to_date('11/3/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (20, 'Aldous', 'Greig', 'Forbes', str_to_date('10/22/1954', '%c/%d/%Y'), 'M', 'SENATOR', 10739, 0, str_to_date('1/22/2014', '%c/%d/%Y'), str_to_date('1/28/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (21, 'Natassia', 'Fetherston', 'Klaiser', str_to_date('07/21/1969', '%c/%d/%Y'), 'F', 'SENATOR', 22617, 1, str_to_date('12/2/2011', '%c/%d/%Y'), str_to_date('3/8/2014', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (22, 'Mel', 'Moyles', 'Trussler', str_to_date('08/26/1952', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 13043, 0, str_to_date('10/3/2009', '%c/%d/%Y'), str_to_date('12/23/2009', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (23, 'Liesa', 'Genney', 'Senechell', str_to_date('08/29/1939', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 31114, 0, str_to_date('12/12/2007', '%c/%d/%Y'), str_to_date('3/26/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (24, 'Auria', 'Tiery', 'McEnery', str_to_date('09/05/1934', '%c/%d/%Y'), 'F', 'SENATOR', 37468, 2, str_to_date('1/9/2011', '%c/%d/%Y'), str_to_date('6/10/2005', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (25, 'Hilarius', 'McFeat', 'Kolodziejski', str_to_date('04/14/1940', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 19175, 1, str_to_date('5/17/2015', '%c/%d/%Y'), str_to_date('4/2/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (26, 'Ringo', 'Runnacles', 'Corzon', str_to_date('12/18/1960', '%c/%d/%Y'), 'M', 'SENATOR', 18873, 0, str_to_date('9/8/2009', '%c/%d/%Y'), str_to_date('7/21/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (27, 'Birch', 'Hevey', 'Finnes', str_to_date('06/29/1943', '%c/%d/%Y'), 'M', 'SENATOR', 14759, 1, str_to_date('5/28/2010', '%c/%d/%Y'), str_to_date('3/6/2019', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (28, 'Fidelia', 'Waye', 'Scholey', str_to_date('04/07/1937', '%c/%d/%Y'), 'F', 'SENATOR', 34703, 0, str_to_date('6/8/2014', '%c/%d/%Y'), str_to_date('2/19/2016', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (29, 'Osmund', 'Pardoe', 'Cossem', str_to_date('04/06/1969', '%c/%d/%Y'), 'M', 'SENATOR', 26150, 1, str_to_date('1/14/2010', '%c/%d/%Y'), str_to_date('7/18/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (30, 'Pearline', 'Buckwell', 'Gaven', str_to_date('08/07/1946', '%c/%d/%Y'), 'F', 'SENATOR', 36310, 2, str_to_date('5/17/2008', '%c/%d/%Y'), str_to_date('6/18/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (31, 'Laurie', 'Creigan', 'Deek', str_to_date('03/31/1970', '%c/%d/%Y'), 'M', 'SENATOR', 35736, 0, str_to_date('6/6/2016', '%c/%d/%Y'), str_to_date('1/29/2004', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (32, 'Joann', 'Featherstonhalgh', 'Henrys', str_to_date('03/31/1970', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 32623, 0, str_to_date('5/12/2011', '%c/%d/%Y'), str_to_date('2/18/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (33, 'Ilene', 'Duthy', 'Ballston', str_to_date('08/21/1961', '%c/%d/%Y'), 'F', 'SENATOR', 31429, 2, str_to_date('10/29/2005', '%c/%d/%Y'), str_to_date('2/21/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (34, 'Emmery', 'Strutt', 'Guyon', str_to_date('08/08/1959', '%c/%d/%Y'), 'M', 'SENATOR', 33879, 1, str_to_date('10/3/2010', '%c/%d/%Y'), str_to_date('5/8/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (35, 'Portie', 'Farquar', 'Yitzhakov', str_to_date('01/21/1932', '%c/%d/%Y'), 'M', 'SENATOR', 26512, 1, str_to_date('3/19/2014', '%c/%d/%Y'), str_to_date('9/2/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (36, 'Ruperto', 'Fort', 'Coats', str_to_date('09/13/1962', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 34347, 2, str_to_date('1/3/2014', '%c/%d/%Y'), str_to_date('7/11/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (37, 'Odelinda', 'Standen', 'Sambidge', str_to_date('08/15/1949', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 20009, 2, str_to_date('2/6/2009', '%c/%d/%Y'), str_to_date('9/26/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (38, 'Alexis', 'Crayker', 'Coltart', str_to_date('04/30/1966', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 29801, 1, str_to_date('10/20/2014', '%c/%d/%Y'), str_to_date('1/18/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (39, 'Ardelle', 'Tows', 'Dimitrov', str_to_date('07/07/1956', '%c/%d/%Y'), 'F', 'SENATOR', 23597, 1, str_to_date('3/15/2012', '%c/%d/%Y'), str_to_date('4/27/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (40, 'Bradford', 'Chalcraft', 'Farndale', str_to_date('03/30/1970', '%c/%d/%Y'), 'M', 'SENATOR', 11878, 0, str_to_date('3/6/2006', '%c/%d/%Y'), str_to_date('12/19/2016', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (41, 'Myrle', 'Joyner', 'Olyfant', str_to_date('05/21/1933', '%c/%d/%Y'), 'F', 'SENATOR', 19837, 0, str_to_date('7/23/2008', '%c/%d/%Y'), str_to_date('11/19/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (42, 'Karlotte', 'Lucock', 'Lusted', str_to_date('01/21/1967', '%c/%d/%Y'), 'F', 'SENATOR', 35931, 0, str_to_date('3/4/2010', '%c/%d/%Y'), str_to_date('12/26/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (43, 'Eddy', 'Fyndon', 'Astles', str_to_date('09/15/1942', '%c/%d/%Y'), 'M', 'SENATOR', 36312, 1, str_to_date('5/21/2015' , '%c/%d/%Y'), str_to_date('5/31/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (44, 'Crissy', 'Lukianovich', 'Katte', str_to_date('01/30/1934', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 18194, 0, str_to_date('8/3/2009', '%c/%d/%Y'), str_to_date('8/28/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (45, 'Barbey', 'Sweeney', 'Canfer', str_to_date('01/15/1970', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 36438, 0, str_to_date('10/10/2007', '%c/%d/%Y'), str_to_date('1/1/2010', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (46, 'Aundrea', 'Benton', 'Posvner', str_to_date('11/25/1968', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 16417, 0, str_to_date('6/4/2008', '%c/%d/%Y'), str_to_date('1/13/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (47, 'Rolf', 'Canning', 'Crowden', str_to_date('03/13/1932', '%c/%d/%Y'), 'M', 'SENATOR', 24591, 1, str_to_date('2/8/2005', '%c/%d/%Y'), str_to_date('12/19/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (48, 'Brockie', 'Gaw', 'Bagley', str_to_date('10/28/1964', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 11781, 2, str_to_date('12/27/2004', '%c/%d/%Y'), str_to_date('7/16/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (49, 'Fran', 'Broadberrie', 'Hamelyn', str_to_date('03/09/1935', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 38082, 0, str_to_date('10/29/2014', '%c/%d/%Y'), str_to_date('9/26/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (50, 'Olin', 'Robardey', 'Leser', str_to_date('05/03/1931', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 15614, 2, str_to_date('1/9/2009', '%c/%d/%Y'), str_to_date('8/8/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (51, 'Barbie', 'Fancott', 'Brosenius', str_to_date('12/11/1937', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 14681, 2, str_to_date('10/7/2005', '%c/%d/%Y'), str_to_date('1/31/2014', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (52, 'Lenette', 'Burghill', 'Schruyer', str_to_date('06/12/1967', '%c/%d/%Y'), 'F', 'SENATOR', 23547, 0, str_to_date('2/24/2008', '%c/%d/%Y'), str_to_date('1/17/2004', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (53, 'Zelda', 'Wyon', 'Melross', str_to_date('04/08/1957', '%c/%d/%Y'), 'F', 'SENATOR', 29861, 1, str_to_date('1/31/2006', '%c/%d/%Y'), str_to_date('1/15/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (54, 'Wilhelm', 'Lanston', 'Delph', str_to_date('02/20/1943', '%c/%d/%Y'), 'M', 'SENATOR', 32669, 2, str_to_date('5/3/2014', '%c/%d/%Y'), str_to_date('3/28/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (55, 'Emmalyn', 'Biddlestone', 'Seckington', str_to_date('06/18/1965', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 23417, 2, str_to_date('9/29/2007', '%c/%d/%Y'), str_to_date('4/26/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (56, 'Augustin', 'Jewers', 'Ellison', str_to_date('03/04/1933', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 21305, 0, str_to_date('5/31/2005', '%c/%d/%Y'), str_to_date('1/13/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (57, 'Martyn', 'Stickel', 'Napoli', str_to_date('12/07/1952', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 10226, 0, str_to_date('10/29/2013', '%c/%d/%Y'), str_to_date('4/24/2004', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (58, 'Hyacinth', 'Radin', 'Sacks', str_to_date('12/06/1964', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 27809, 0, str_to_date('11/24/2011', '%c/%d/%Y'), str_to_date('9/22/2016', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (59, 'Kerby', 'Stollmeier', 'Steart', str_to_date('12/06/1964', '%c/%d/%Y'), 'M', 'SENATOR', 14350, 1, str_to_date('4/3/2007', '%c/%d/%Y'), str_to_date('6/11/2019', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (60, 'Allys', 'Sneaker', 'Wadworth', str_to_date('11/16/1940', '%c/%d/%Y'), 'F', 'SENATOR', 30707, 0, str_to_date('1/23/2014', '%c/%d/%Y'), str_to_date('1/4/2016', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (61, 'Cordy', 'Farrance', 'Dumphries', str_to_date('09/11/1936', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 35583, 1, str_to_date('3/25/2004', '%c/%d/%Y'), str_to_date('7/31/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (62, 'Mortie', 'Grzegorzewicz', 'Rosbrough', str_to_date('08/31/1960', '%c/%d/%Y'), 'M', 'SENATOR', 39532, 0, str_to_date('5/21/2006', '%c/%d/%Y'), str_to_date('8/2/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (63, 'Benedikt', 'Grestie', 'Sandeford', str_to_date('04/04/1967', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 16126, 0, str_to_date('6/26/2008', '%c/%d/%Y'), str_to_date('10/28/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (64, 'Maison', 'Goodings', 'Motton', str_to_date('03/18/1937', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 34476, 1, str_to_date('6/2/2010', '%c/%d/%Y'), str_to_date('8/26/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (65, 'Kin', 'Gilderoy', 'Divall', str_to_date('11/05/1960', '%c/%d/%Y'), 'M', 'SENATOR', 18091, 1, str_to_date('7/26/2008', '%c/%d/%Y'), str_to_date('10/12/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (66, 'Burnaby', 'Hoffmann', 'Dodshun', str_to_date('04/15/1967', '%c/%d/%Y'), 'M', 'SENATOR', 23746, 0, str_to_date('6/12/2015', '%c/%d/%Y'), str_to_date('1/25/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (67, 'Stearne', 'Antonsen', 'Crystal', str_to_date('04/30/1954', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 14026, 1, str_to_date('1/8/2008', '%c/%d/%Y'), str_to_date('7/18/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (68, 'Hillyer', 'Stebbing', 'Winwright', str_to_date('05/20/1943', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 22483, 0, str_to_date('3/25/2006', '%c/%d/%Y'), str_to_date('1/25/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (69, 'Riccardo', 'Torrejon', 'Keeton', str_to_date('05/09/1964', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 27647, 0, str_to_date('9/26/2012', '%c/%d/%Y'), str_to_date('8/16/2010', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (70, 'Donelle', 'Kerner', 'Leban', str_to_date('11/29/1962', '%c/%d/%Y'), 'F', 'SENATOR', 27195, 2, str_to_date('11/23/2014', '%c/%d/%Y'), str_to_date('3/1/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (71, 'Dennie', 'Dunthorne', 'Nicklen', str_to_date('02/25/1938', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 36656, 2, str_to_date('1/25/2013', '%c/%d/%Y'), str_to_date('12/5/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (72, 'Conny', 'Cleary', 'Flode', str_to_date('07/18/1952', '%c/%d/%Y'), 'M', 'SENATOR', 12461, 2, str_to_date('5/20/2007', '%c/%d/%Y'), str_to_date('2/4/2004', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (73, 'Carolin', 'Johnston', 'Schoenleiter', str_to_date('11/26/1962', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 25606, 1, str_to_date('2/8/2013', '%c/%d/%Y'), str_to_date('3/26/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (74, 'Meridith', 'Kosel', 'Rilston', str_to_date('03/11/1943', '%c/%d/%Y'), 'F', 'SENATOR', 10797, 2, str_to_date('12/16/2008', '%c/%d/%Y'), str_to_date('9/13/2019', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (75, 'Verena', 'Prater', 'Gronowe', str_to_date('05/02/1938', '%c/%d/%Y'), 'F', 'SENATOR', 20213, 1, str_to_date('3/23/2015', '%c/%d/%Y'), str_to_date('7/29/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (76, 'Sherlocke', 'Tetlow', 'Ficken', str_to_date('10/09/1932', '%c/%d/%Y'), 'M', 'SENATOR', 38354, 1, str_to_date('8/4/2004', '%c/%d/%Y'), str_to_date('7/8/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (77, 'Terrye', 'Bridie', 'Emblen', str_to_date('12/04/1961', '%c/%d/%Y'), 'F', 'SENATOR', 20499, 0, str_to_date('12/4/2012', '%c/%d/%Y'), str_to_date('7/11/2005', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (78, 'Nikolai', 'Pach', 'Escala', str_to_date('11/13/1961', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 16668, 2, str_to_date('3/25/2014', '%c/%d/%Y'), str_to_date('11/20/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (79, 'Jolyn', 'Stebbin', 'Roos', str_to_date('04/01/1946', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 17171, 1, str_to_date('8/22/2007', '%c/%d/%Y'), str_to_date('9/18/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (80, 'Archer', 'Bruno', 'Kleinberer', str_to_date('05/13/1956', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 17688, 0, str_to_date('4/12/2005', '%c/%d/%Y'), str_to_date('12/7/2013', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (81, 'Jourdain', 'Lehrer', 'O''Bradain', str_to_date('12/29/1940', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 21149, 2, str_to_date('5/29/2014', '%c/%d/%Y'), str_to_date('12/27/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (82, 'Kimberlyn', 'Hellwich', 'Minichi', str_to_date('02/28/1943', '%c/%d/%Y'), 'F', 'SENATOR', 24180, 2, str_to_date('5/27/2009', '%c/%d/%Y'), str_to_date('5/1/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (83, 'Prudi', 'Baish', 'Godfree', str_to_date('08/27/1933', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 10592, 2, str_to_date('4/29/2011', '%c/%d/%Y'), str_to_date('4/25/2017', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (84, 'Cleon', 'Aristide', 'Itzchaki', str_to_date('05/18/1965', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 10400, 1, str_to_date('11/8/2013', '%c/%d/%Y'), str_to_date('12/23/2011', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (85, 'Lulu', 'McNee', 'McQuorkell', str_to_date('08/27/1940', '%c/%d/%Y'), 'F', 'SENATOR', 11445, 1, str_to_date('7/5/2008', '%c/%d/%Y'), str_to_date('1/17/2013', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (86, 'Nanine', 'Riquet', 'Manning', str_to_date('08/14/1932', '%c/%d/%Y'), 'F', 'SENATOR', 36560, 0, str_to_date('5/22/2009', '%c/%d/%Y'), str_to_date('3/1/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (87, 'Frederic', 'Cotmore', 'McVane', str_to_date('07/04/1955', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 27375, 0, str_to_date('12/12/2014', '%c/%d/%Y'), str_to_date('4/5/2015', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (88, 'Bettye', 'McClintock', 'Ladewig', str_to_date('06/13/1957', '%c/%d/%Y'), 'F', 'SENATOR', 15871, 0, str_to_date('10/2/2012', '%c/%d/%Y'), str_to_date('7/6/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (89, 'Dell', 'Turle', 'Argo', str_to_date('08/09/1967', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 25066, 1, str_to_date('7/23/2016', '%c/%d/%Y'), str_to_date('7/31/2006', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (90, 'Hewett', 'Oakenfall', 'Wiersma', str_to_date('11/03/1969', '%c/%d/%Y'), 'M', 'SENATOR', 19150, 2, str_to_date('9/9/2007', '%c/%d/%Y'), str_to_date('6/15/2004', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (91, 'Sarena', 'Laughlan', 'Rentcome', str_to_date('02/08/1937', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 23925, 0, str_to_date('5/12/2009', '%c/%d/%Y'), str_to_date('1/5/2014', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (92, 'Merwin', 'Eads', 'Brameld', str_to_date('05/20/1967', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 15199, 0, str_to_date('10/29/2006', '%c/%d/%Y'), str_to_date('8/21/2018', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (93, 'Johannes', 'Whyler', 'Tootal', str_to_date('12/15/1960', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 39559, 2, str_to_date('6/8/2012', '%c/%d/%Y'), str_to_date('6/3/2005', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (94, 'Evin', 'Macro', 'Chastney', str_to_date('04/03/1955', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 39538, 0, str_to_date('3/14/2013', '%c/%d/%Y'), str_to_date('9/23/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (95, 'Chilton', 'Radbond', 'Draisey', str_to_date('02/27/1951', '%c/%d/%Y'), 'M', 'SENATOR', 14543, 0, str_to_date('11/5/2011', '%c/%d/%Y'), str_to_date('11/6/2007', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (96, 'Durward', 'Gloyens', 'Bidewell', str_to_date('10/07/1965', '%c/%d/%Y'), 'M', 'SENATOR', 33409, 2, str_to_date('3/19/2005', '%c/%d/%Y'), str_to_date('10/24/2016', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (97, 'Paulette', 'Varsey', 'Jollands', str_to_date('05/19/1937', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 27773, 1, str_to_date('4/12/2012', '%c/%d/%Y'), str_to_date('4/16/2008', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (98, 'Maren', 'Jobbins', 'Dodgshon', str_to_date('05/18/1948', '%c/%d/%Y'), 'F', 'SENATOR', 35510, 1, str_to_date('12/14/2012', '%c/%d/%Y'), str_to_date('12/1/2016', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (99, 'Lona', 'Belch', 'Bell', str_to_date('11/14/1967', '%c/%d/%Y'), 'F', 'HOUSEMEMBER', 36251, 2, str_to_date('1/28/2007', '%c/%d/%Y'), str_to_date('4/25/2012', '%c/%d/%Y'));
insert into legislator (empid, fname, mname, lname, bday, sex, type, sal, noofterms, termstart, termend) values (100, 'Fowler', 'Stainer', 'Poor', str_to_date('06/20/1930', '%c/%d/%Y'), 'M', 'HOUSEMEMBER', 36570, 0, str_to_date('6/24/2005', '%c/%d/%Y'), str_to_date('4/15/2014', '%c/%d/%Y'));

insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (1, 'Diverting Attention from Data in Project', 'Act to divert attention from dummy data included in project and focus on functionality', 'House Bill', 'National', 'Pending', '2nd', str_to_date('04/11/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (2, 'Parking Space for Handicapped Persons Act of 2017', 'An Act Mandating the Provision of Exclusive Parking Space for Handicapped Persons and Penalizing the Unauthorized Use Thereof', 'House Bill', 'National', 'Pending', '3rd', str_to_date('08/26/2016', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (3, 'Nutritional Information Disclosure Act of 2017', 'An Act Requiring the Disclosure of Nutritional Information in Menus of Food Service Establishments', 'House Bill', 'National', 'Pending', '2nd', str_to_date('06/30/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (4, 'Clean Code', 'Act to create understandable and modifiable code', 'House Bill', 'National', 'Pending', '1st', str_to_date('08/01/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (5, 'Refactoring condensed code', 'Act to force programmers to create smaller methods and functions', 'House Bill', 'National', 'Pending', '3rd', str_to_date('07/14/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (6, 'Use of distributed model of repositories', 'creating distributed repository with one central repository on cloud server', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('03/01/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (7, 'Copyright', 'Intellectual property assurance', 'House Bill', 'National', 'Passed', '3rd', str_to_date('12/24/2012', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (8, 'Randomly Generated Data', 'Leila de Lima alleged sex video', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('04/14/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (9, 'Meaningless text', 'Contents of Mocha Uson Blog', 'House Bill', 'National', 'Pending', '1st', str_to_date('03/18/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (10, 'Discriminative Factor', '', 'Senate Bill', 'National', 'Pending', '2nd', str_to_date('05/15/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (11, 'Platform Independence', 'Project build should be runnable on multiple software platforms', 'Senate Bill', 'National', 'Pending', '1st', str_to_date('08/04/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (12, 'Delivery of ring to Mordor', 'Act to destroy the Dark Lord, Sauron', 'House Bill', 'National', 'Passed', '1st', str_to_date('07/28/2016', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (13, 'Forming Alliance with China', 'Domestication of Philippines as pet', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('02/27/2010', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (14, 'Abolishment of Military Regimes', '', 'House Bill', 'National', 'Pending', '2nd', str_to_date('06/07/2016', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (15, 'Recoverable System Loss Act', 'An Act Reducing the Cap of Recoverable System Loss Rate and for Other Purposes', 'House Bill', 'National', 'Passed', '2nd', str_to_date('11/08/2012', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (16, 'Employee Wellness', 'Act to prioritize health and sleep of employees', 'Senate Bill', 'National', 'Pending', '1st', str_to_date('05/08/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (17, 'Excise Tax on Tobacco Products', 'An Act Raising the Excise Tax on Tobacco Products and Amending for the Purpose Pertinent Sections of the National Internal Revenue Code', 'Senate Bill', 'National', 'Passed', '3rd', str_to_date('03/08/2012', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (18, 'Batas Kasambahay Social Security Condonation Law of 2017', 'An Act Granting the Social Security System the Authority to Condone Penalties for UNRemitted or Delinquent Contributions by Employers of Domestic Workers', 'House Bill', 'National', 'Passed', '2nd', str_to_date('06/24/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (19, 'Student Fare Discount Act', 'An Act Institutionalizing the Grant of Student Fare Discount Privileges on Public Transportation and for Other Purposes', 'Senate Bill', 'National', 'Passed', '3rd', str_to_date('06/15/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (20, 'Yolanda Commemoration Day', 'An Act Declaring November 8 of Every Year a Special Nonworking Public Holiday in the Eastern Visayas Region to Be Known as the Yolanda Commemoration Day', 'House Bill', 'National', 'Passed', '3rd',str_to_date('08/10/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (21, 'Transnational Higher Education Act', 'An Act Providing for the Legal Framework and Mechanisms for the Creation, Operation, and Administration of Transnational Higher Education in the Philippines', 'House Bill', 'National', 'Passed', '3rd', str_to_date('01/25/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (22, 'Tax Reform Acceleration and Inclusion (Train)', 'An Act Amending Sections 5, 6, 24, 25, 31, 34, 35, 51, 79, 84, 86, 89, 90, 97, 99, 100, 101, 106, 107, 108, 109, 112, 114, 116, 148, 149, 150, 151, 155, 171, 196, 232, 237, 249, 264', 'House Bill', 'National', 'Pending', '3rd', str_to_date('08/26/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (23, 'Anti-Hazing Act of 2017', 'An Act Prohibiting Hazing and Regulating Other Forms of Initiation Rites of Fraternities, Sororities, and Other Organizations', 'Senate Bill', 'National', 'Passed', '1st', str_to_date('07/12/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (24, 'Renewing and Amending the Franchise of Innove Communications, Inc.', 'An Act Renewing and Amending the Franchise Granted to Innove Communications, Inc. (Formerly ‘Isla Communications, Co.) ', 'House Bill', 'National', 'Passed', '2nd', str_to_date('10/08/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (25, 'South Cotabato State College in Surallah, South Cotabato', 'An Act Establishing the South Cotabato State College in the Municipality of Surallah, Province of South Cotabato, Integrating Therewith the Surallah National Agricultural School', 'Senate Bill', 'National', 'Pending', '1st', str_to_date('10/18/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (26, 'Soccsksargen General Hospital in Surallah, South Cotabato', 'An Act Establishing the Soccsksargen General Hospital in the Municipality of Surallah, Province of the South Cotabato, and Appropriating Funds Therefor ', 'House Bill', 'National', 'Pending', '3rd', str_to_date('05/13/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (27, 'Body Camera for Law Enforcement Personnel Act of 2017', 'An Act Mandating Law Enforcement Personnel to Wear a Body Camera During Law Enforcement and Special Police Opeations, Providing Funds Therefor and for Other Purposes', 'Senate Bill', 'National', 'Pending', '2nd', str_to_date('09/13/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (28, 'Postponing the October 2017 Barangay and Sangguniang Kabataan Elections', 'An Act Postponing the October 2017 Barangay and Sangguniang Kabataan Elections, Amending for the Purpose Republic Act No. 9164', 'House Bill', 'National', 'Passed', '3rd', str_to_date('11/12/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (29, 'Local School Board Act', 'An Act Strengthening the Local School Boards in the Philippines', 'Senate Bill', 'National', 'Passed', '2nd', str_to_date('05/13/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (30, 'Drugs Price Regulatory Board', 'An Act Establishing the Drug Price Regulatory Board to Regulate the Prices of Drugs and Medicines in the Philippines ', 'Senate Bill', 'National', 'Passed', '2nd', str_to_date('08/17/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (31, 'Land Transportation Office (LTO) in the City of Valencia, Bukidnon', 'An Act Establishing a Land Transport Office (LTO) in the City of Valencia, Province of Bukidnon and Appropriating Funds Therefor', 'House Bill', 'National', 'Pending', '3rd', str_to_date('08/26/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (32, 'Filipino Identification System Act', 'An Act Establishing the Filipino Identification Sytem', 'Senate Bill', 'National', 'Passed', '1st', str_to_date('08/20/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (33, 'Department of Human Settlements and Urban Development Act of 2017', 'An Act Creating the Department of Human Settlements and Urban Development, Defining its Mandates, Powers and Functions, Providing Funds Therefor and for Other Purposes', 'House Bill', 'National', 'Passed', '1st', str_to_date('10/03/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (34, 'Filipino Identification System Act', 'An Act Establishing the Filipino Identification System', 'House Bill', 'National', 'Passed', '3rd', str_to_date('12/17/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (35, 'Police On-Body Cam Act', 'An Act Mandating the Use of On-Body Cameras by Law Enforcement Officers During Any Anti-Illegal Drug and Criminality Operations, and Providing Funds Therefor', 'House Bill', 'National', 'Pending', '3rd', str_to_date('04/11/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (36, 'Increasing the Age for Determining Statutory Rape to Provide Stronger Protection for Children', 'An Act Increasing the Age for Determining Statutory Rape to Provide Stronger Protection for Children', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('05/29/2010', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (37, 'Philippine Energy Research and Policy Institute Act of 2017', 'An Act Establishing the Philippine Energy Research and Policy Institute, Defining its Objectives, Powers and Functions, Providing Funds Therefor', 'Senate Bill', 'National', 'Pending', '1st', str_to_date('12/10/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (38, 'Emergency Medical Services Systems (EMMS) Act', 'An Act Institutionalizing An Emergency Medical Services System, Providing for the Establishment, Supervision and Regulation of Emergency Medical Services Profession, and Appropriating Funds', 'Senate Bill', 'National', 'Pending', '2nd', str_to_date('11/15/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (39, 'Philippine Space Development Act', 'An Act Establishing the Philippine Space Development and Utilization Policy, Providing Funds Therefor, and for Other Purposes ', 'House Bill', 'National', 'Passed', '3rd', str_to_date('04/15/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (40, 'National Integrated Cancer Control Act', 'An Act Institutionalizing National Integrated Cancer Control and Appropriating Funds', 'Senate Bill', 'National', 'Passed', '2nd', str_to_date('06/23/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (41, 'Creating a Dental Unit in Every Rural Health Unit', 'An Act Creating a Dental Unit in Every Rural Health Unit Under the Department of Health as Part of the Primary Approach in the Delivery of Health Services and Providing Funds', 'House Bill', 'National', 'Pending', '2nd', str_to_date('02/13/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (42, 'Sustainable Transportation Act of 2017', 'An Act Promoting Sustainable and Alternative Modes of Transportation and Other Mobility Options to Improve Air Quality, Increase Efficiency', 'House Bill', 'National', 'Pending', '2nd', str_to_date('08/23/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (43, 'Tabang Marawi Fund of 2017', 'An Act Appropriating the Amount of Ten Billion Pesos for the Rehabilitation and Reconstruction of Marawi City and Other Municipalities in the Province of Lanao Del Sur', 'Senate Bill', 'National', 'Pending', '1st', str_to_date('10/20/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (44, 'Night Shift Differential Pay to the Government Employees', 'An Act Granting Night Shift Differential Pay to the Government Employees Including Those in Government-Owned or Controlled Corporations and Appropriating Funds', 'House Bill', 'National', 'Passed', '1st', str_to_date('04/10/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (45, 'Contractual and Casual Employeees Wages During Special Public and Local Holidays', 'An Act Providing That All Contractual and Casual Employees in the Government Service Be Paid Corresponding Wages', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('04/19/2012', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (46, 'Disaster Service Volunteer Leave Act of 2017', 'An Act Granting Disaster Service Volunteers Paid Leave During Period of Disasters', 'Senate Bill', 'National', 'Passed', '1st', str_to_date('12/02/2012', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (47, 'Hazard Pay to Government Employees', 'An Act Granting Hazard Pay to Covered Employees of the Government and Appropriating Funds', 'House Bill', 'National', 'Pending', '3rd', str_to_date('11/09/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (48, 'Safe Streets, Workplaces and Public Spaces Act of 2017', 'An Act Defining and Penalizing Gender-Based Street and Public Spaces Harassment, Expanding the Definition of Sexual Harassment, and Amending for This Purpose', 'Senate Bill', 'National', 'Passed', '2nd', str_to_date('12/03/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (49, 'Salary Grade 1, Increase Salary From Php9,000.00 to Php11,068.00', 'An Act Modifying the Salary Schedule for Civilian Government Personnel and Authorizing the Grant of Additional Benefits for Both Civilian and Military and Uniformed Personnel', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('01/24/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (50, 'Philippine Immigration and Registration of Foreign Nationals Act', 'An Act Creating the Commission on Immigration, Defining its Powers and Functions, Expanding, Rationalizing', 'House Bill', 'National', 'Passed', '3rd', str_to_date('12/11/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (51, 'Palliative and Hospice Care Act', 'An Act Integrating Palliative and Hospice Care Into the Philippine Health Care System', 'House Bill', 'National', 'Pending', '2nd', str_to_date('04/04/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (52, 'Abolishing the Road Board as the Regulatory Agency of the Motor Vehicle Users Charge', 'An Act Abolishing the Road Board as the Regulatory Agency of the Motor Vehicle User’S Charge (MVUC)', 'Senate Bill', 'National', 'Pending', '2nd', str_to_date('04/04/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (53, 'Department of Disaster and Emergency Management Act of 2017', 'An Act Creating the Department of Disaster and Emergency Management, Defining its Powers and Functions, Appropriating Funds', 'House Bill', 'National', 'Passed', '3rd', str_to_date('08/13/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (54, 'Postponing the October 2017 Barangay and Sangguniang Kabataan Elections', 'An Act Postponing the October 2017 Barangay and Sangguniang Kabataan Elections', 'House Bill', 'National', 'Passed', '2nd', str_to_date('02/13/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (55, 'Special Non-Working Holiday in the Province of Sultan Kudarat', 'An Act Declaring November 22 of Every Year as a Special Nonworking Holiday in the Province of Sultan Kudarat Filed', 'Senate Bill', 'National', 'Passed', '1st', str_to_date('08/31/2010', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (56, 'Amending R.A. No. 6977, as Amended (Magna Carta for Small Enterprises)', 'An Act Redefining the Coverage and Extending the Mandatory Credit Allocation to Micro, Small and Medium Enterprises, Amending for the Purpose Certain Provisions', 'House Bill', 'National', 'Pending', '2nd', str_to_date('06/25/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (57, 'Science for Change Program (SCP) Act of 2017', 'An Act Establishing the Science for Change Program', 'House Bill', 'National', 'Passed', '3rd', str_to_date('07/18/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (58, 'Reversion to Maiden Name Act', 'An Act Allowing Women to Revert to Their Maiden Surname, Establishing a Procedure for Reversion and Appropriating Funds ', 'Senate Bill', 'National', 'Pending', '2nd', str_to_date('04/17/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (59, 'Primary Care Provider Recruitment Act of 2017', 'An Act Creating Primary Care Retraining and Scholarship Programs for the Recruitment of Qualified Filipinos Who Will Serve as Primary Care Workers', 'Senate Bill', 'National', 'Passed', '3rd', str_to_date('08/06/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (60, 'National Integrated Cancer Control Act', 'An Act Institutionalizing National Integrated Cancer Control and Appropriating Funds', 'House Bill', 'National', 'Pending', '2nd', str_to_date('03/07/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (61, 'PNP Modernization Act of 2017', 'An Act Providing for the Modernization of the Philippine National Police, Appropriating Funds Therefor, and for Other Purposes ', 'House Bill', 'National', 'Passed', '3rd', str_to_date('05/11/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (62, 'Special Protection of Children in Situations of Armed Conflict Act of 2017', 'An Act Providing for the Special Protection of Children in Situations of Armed Conflict and Providing Penalties for Violations ', 'House Bill', 'National', 'Passed', '1st', str_to_date('07/13/2010', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (63, 'Creating Two (2) Additional Branches of the Rtc in the Province of Sultan Kudarat', 'An Act Creating Two (2) Additional Branches of the Regional Trial Court in the Province of Sultan Kudarat, One Each to Be Stationed in the Municipality of Isulan', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('09/22/2016', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (64, 'Increasing the Excise Tax on Nonmetallic and Metallic Minerals and Mineral Products', 'An Act Increasing the Excise Tax on Nonmetallic and Metallic Minerals and Mineral Products, and Quarry Resources', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('11/10/2010', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (65, 'Electric and Hybrid Vehicles Including Charging Stations Promotions Act of 2017', 'An Act Promoting Environmentally Sustainable Transport by Providing Incentives for the Manufacture, Assembly, Conversion and Importation of Electric and Hybrid Vehicles Including Charging', 'Senate Bill', 'National', 'Passed', '1st', str_to_date('04/14/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (66, 'Namcya Act of 2017', 'An Act Designating the National Music Competitions for Young Artists (Namcya) as the National Youth Development Program for Music, Defining its Role and Functions as Such', 'Senate Bill', 'National', 'Passed', '2nd', str_to_date('03/03/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (67, 'Vaporized Nicotine Products Regulation Act', 'An Act Regulating Vaporized Nicotine Products', 'House Bill', 'National', 'Passed', '1st', str_to_date('12/31/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (68, 'The Healthy Nanay and Bulilit Act', 'An Act Providing for the Scaling Up of Nutrition for the First 1,000 Days of Life Through a Strengthened Integrated Strategy for Maternal,Neonatal, Child Health and Nutrition', 'House Bill', 'National', 'Pending', '3rd', str_to_date('07/20/2016', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (69, 'No Permit, No Exam Act of 2017', 'An Act Penalizing the Imposition of a ‘No Permit, No Exam’ Policy or Any Such Policy That Prohibits Students in All Educational Institutions From Taking Their Periodic, Preliminary, Midterm', 'Senate Bill', 'National', 'Passed', '3rd', str_to_date('02/29/2016', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (70, 'Anti-Epal Law', 'An Act Prohibiting Incumbent Government Officials to Name Government Projects After Them or Other Persons Whose Name or Identity May in Any Manner Be Associated with Said Officials', 'House Bill', 'National', 'Pending', '3rd', str_to_date('12/17/2012', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (71, 'Magna Carta for Scientist, Engineers, Researchers', 'An Act Amending Republic Act No. 8439, Otherwise Known as the Magna Carta for Scientists, Engineers, Researchers and Other', 'House Bill', 'National', 'Passed', '1st', str_to_date('05/11/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (72, 'Balik Scientist Act', 'An Act Institutionalizing the Balik Scientist Program, Appropriating Funds Therefor, and for Other Purpose Filed ', 'House Bill', 'National', 'Passed', '3rd', str_to_date('07/03/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (73, 'Innovative Startup Act', 'An Act Providing Benefits and Programs to Strengthen, Promote, and Develop the Philippine Startup Ecosystem', 'Senate Bill', 'National', 'Passed', '3rd', str_to_date('03/27/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (74, 'Energy Efficiency and Conservation Act of 2017', 'An Act Institutionalizing Energy Efficiency and Conservation, Enhancing the Efficient Use of Energy, Granting Incentives to Energy Efficiency and Conservation Projects', 'Senate Bill', 'National', 'Passed', '3rd', str_to_date('08/27/2016', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (75, 'Augmenting Survivorship Benefits of Heirs of Soldiers Who Died in Line of Duty', 'An Act Augmenting Survivorship Benefits of Heirs of Soldiers Who Died in the Line of Duty Before Completion of Twenty Years of Active Service', 'Senate Bill', 'National', 'Passed', '3rd', str_to_date('02/21/2010', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (76, 'National Museum of the Philippines Act', 'An Act Strengthening the National Museum of the Philippines, Repealing for the Purpose Republic Act No. 8492', 'House Bill', 'National', 'Pending', '3rd', str_to_date('06/18/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (77, 'Department of Culture Act', 'An Act Establishing the Department of Culture, Appropriating Funds Therefor, and for Other Purposes', 'House Bill', 'National', 'Pending', '3rd', str_to_date('08/08/2012', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (78, 'British School Manila as An Educational Institution of International Character', 'An Act Recognizing the British School Manila as An Educational Institution of International Character, Granting Certain Prerogatives Conducive', 'Senate Bill', 'National', 'Passed', '2nd', str_to_date('02/14/2012', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (79, 'The First Philippine Republic Day', 'An Act Declaring January 23 of Every Year a Special Working Holiday in the Entire Country to Commemorate the Declaration of the First Philippine Republic', 'Senate Bill', 'National', 'Passed', '2nd', str_to_date('03/22/2016', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (80, 'Green Vehicles Incentives Act', 'An Act Providing Incentives for the Manufacture, Assembly, Conversion and Importation of Green Vehicles, and for Other Purposes', 'Senate Bill', 'National', 'Passed', '1st', str_to_date('12/22/2010', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (81, 'Environmental Protection Agency Act of 2017', 'An Act Creating the Environmental Protection Agency of the Philippines', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('01/11/2012', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (82, 'National Land Use Act of 2017', 'An Act Instituting a National Land Use Policy, Providing the Implementing Mechanisms Therefor, and for Other Purposes', 'House Bill', 'National', 'Pending', '2nd', str_to_date('04/23/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (83, 'Anti-Overloading Act of 2017', 'An Act Increasing the Penalty for Overloading of Passengers And/Or Freight or Cargo in Common Carriers Beyond the Registered Carrying CapacityBloodborne Viral Hepatitis Testing Act of 2017', 'House Bill', 'National', 'Passed', '3rd', str_to_date('11/28/2016', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (84, 'Bloodborne Viral Hepatitis Testing Act of 2017', 'An Act Instituting a Policy on Bloodborne Viral Hepatitis Testing and Screening', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('07/26/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (85, 'Child Internet Safety and Protection Act of 2017', 'An Act Providing Internet Safety and Protection for Children', 'Senate Bill', 'National', 'Passed', '3rd', str_to_date('09/22/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (86, 'Philippine Amateur Sports Training Center Act', 'An Act Creating and Establishing a State-Of The-Art and Highly Scientific Sports Complex Known as the Philippine Amateur Sports Training Center', 'Senate Bill', 'National', 'Passed', '2nd', str_to_date('02/02/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (87, 'The Expanded Philippine Sports Commission Act of 2017', 'An Act Strengthening the Philippine Sports Commission, Amending for the Purpose', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('05/06/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (88, 'Agri-Food Terminal and Trading Centers Act of 2017', 'An Act Mandating the Establishment of Agri-Food Terminals and Trading Centers in Every Province Providing Funds', 'Senate Bill', 'National', 'Passed', '3rd', str_to_date('03/27/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (89, 'Rights of Internally Displaced Persons Act (Ridpa)', 'An Act Protecting the Rights of Internally Displaced Persons and Appropriating Funds Therefor and for Other Purposes', 'Senate Bill', 'National', 'Passed', '1st', str_to_date('11/20/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (90, 'Tulong Kabataan Sa Agrikultura Act of 2017', 'An Act Encouraging Youth Sector Participation in the Agricultural Sector, Establishing for the Purpose', 'House Bill', 'National', 'Pending', '3rd', str_to_date('08/31/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (91, 'Citizenship Retention and Re-Acquisition Act', 'An Act Amending Section 5, Paragraph 3 of Republic Act No. 9225', 'House Bill', 'National', 'Pending', '3rd', str_to_date('08/05/2017', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (92, 'Filipino Identification System Act', 'An Act Establishing the Filipino Identification System, Providing Funds Therefor, and for Other Purposes', 'House Bill', 'National', 'Passed', '3rd', str_to_date('10/02/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (93, 'Dialysis Center Act', 'An Act Requiring the Establishment of Dialysis Clinics in All National, Regional and Provincial Hospitals and Providing for Free Dialysis Treatments to Indigent Patients and Appropriating', 'House Bill', 'National', 'Pending', '3rd', str_to_date('09/08/2011', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (94, 'Gabaldon School Buildings Conservation Act', 'An Act Mandating the Conservation of Gabaldon School Buildings Nationwide, Providing Penalties for Violations, and Appropriating Funds', 'Senate Bill', 'National', 'Pending', '2nd', str_to_date('05/17/2013', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (95, 'Philippine Arts in Venice Biennale Act of 2017', 'An Act Institutionalizing Philippine Participation in the International Exhibitions of the Venice Biennale', 'House Bill', 'National', 'Pending', '3rd', str_to_date('01/04/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (96, 'Victims Bill of Rights Act of 2017', 'An Act Providing for a Bill of Rights for Victims of Crimes', 'House Bill', 'National', 'Pending', '2nd', str_to_date('08/22/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (97, 'Transportation Network Service Act', 'An Act Recognizing Transportation Network Companies and Drivers', 'Senate Bill', 'National', 'Pending', '2nd', str_to_date('05/25/2016', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (98, 'Filipino Identification System Act', 'An Act Establishing the Filipino Identification System, Providing Funds Therefor, and for Other Purposes', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('11/08/2014', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (99, 'Online Child Safety Act', 'An Act Requiring Commercial Establishments and Public Institutions to Use Appropriate Filtering Devices and Firewalls That Will Restrict Childrens Access to Harmful Materials', 'Senate Bill', 'National', 'Pending', '3rd', str_to_date('08/17/2015', '%c/%d/%Y'));
insert into bill (billno, title, body, billtype, scope, status, reading, datefiled) values (100, 'To Harmonize Legal Education', 'An Act to Harmonize Legal Education in Our Country', 'House Bill', 'National', 'Pending', '3rd', str_to_date('05/05/2012', '%c/%d/%Y'));

insert into bill_author (billno, empid) values (84, 28);
insert into bill_author (billno, empid) values (31, 22);
insert into bill_author (billno, empid) values (65, 98);
insert into bill_author (billno, empid) values (21, 66);
insert into bill_author (billno, empid) values (23, 38);
insert into bill_author (billno, empid) values (44, 93);
insert into bill_author (billno, empid) values (2, 6);
insert into bill_author (billno, empid) values (50, 51);
insert into bill_author (billno, empid) values (5, 92);
insert into bill_author (billno, empid) values (68, 29);
insert into bill_author (billno, empid) values (29, 57);
insert into bill_author (billno, empid) values (75, 29);
insert into bill_author (billno, empid) values (79, 9);
insert into bill_author (billno, empid) values (68, 69);
insert into bill_author (billno, empid) values (55, 91);
insert into bill_author (billno, empid) values (14, 12);
insert into bill_author (billno, empid) values (73, 77);
insert into bill_author (billno, empid) values (80, 5);
insert into bill_author (billno, empid) values (67, 31);
insert into bill_author (billno, empid) values (4, 44);
insert into bill_author (billno, empid) values (77, 37);
insert into bill_author (billno, empid) values (78, 60);
insert into bill_author (billno, empid) values (71, 89);
insert into bill_author (billno, empid) values (87, 28);
insert into bill_author (billno, empid) values (1, 81);
insert into bill_author (billno, empid) values (21, 100);
insert into bill_author (billno, empid) values (11, 78);
insert into bill_author (billno, empid) values (46, 11);
insert into bill_author (billno, empid) values (28, 2);
insert into bill_author (billno, empid) values (58, 47);
insert into bill_author (billno, empid) values (20, 40);
insert into bill_author (billno, empid) values (93, 89);
insert into bill_author (billno, empid) values (48, 86);
insert into bill_author (billno, empid) values (95, 55);
insert into bill_author (billno, empid) values (28, 48);
insert into bill_author (billno, empid) values (76, 27);
insert into bill_author (billno, empid) values (10, 23);
insert into bill_author (billno, empid) values (82, 10);
insert into bill_author (billno, empid) values (61, 11);
insert into bill_author (billno, empid) values (75, 54);
insert into bill_author (billno, empid) values (12, 28);
insert into bill_author (billno, empid) values (43, 12);
insert into bill_author (billno, empid) values (57, 18);
insert into bill_author (billno, empid) values (77, 30);
insert into bill_author (billno, empid) values (56, 40);
insert into bill_author (billno, empid) values (60, 29);
insert into bill_author (billno, empid) values (52, 68);
insert into bill_author (billno, empid) values (42, 67);
insert into bill_author (billno, empid) values (78, 99);
insert into bill_author (billno, empid) values (24, 46);
insert into bill_author (billno, empid) values (12, 69);
insert into bill_author (billno, empid) values (50, 45);
insert into bill_author (billno, empid) values (18, 54);
insert into bill_author (billno, empid) values (37, 88);
insert into bill_author (billno, empid) values (20, 27);
insert into bill_author (billno, empid) values (97, 90);
insert into bill_author (billno, empid) values (87, 100);
insert into bill_author (billno, empid) values (3, 81);
insert into bill_author (billno, empid) values (66, 92);
insert into bill_author (billno, empid) values (27, 65);
insert into bill_author (billno, empid) values (39, 35);
insert into bill_author (billno, empid) values (65, 98);
insert into bill_author (billno, empid) values (34, 6);
insert into bill_author (billno, empid) values (42, 99);
insert into bill_author (billno, empid) values (60, 45);
insert into bill_author (billno, empid) values (92, 19);
insert into bill_author (billno, empid) values (47, 41);
insert into bill_author (billno, empid) values (85, 16);
insert into bill_author (billno, empid) values (72, 29);
insert into bill_author (billno, empid) values (18, 90);
insert into bill_author (billno, empid) values (16, 44);
insert into bill_author (billno, empid) values (14, 84);
insert into bill_author (billno, empid) values (17, 77);
insert into bill_author (billno, empid) values (79, 41);
insert into bill_author (billno, empid) values (20, 84);
insert into bill_author (billno, empid) values (59, 30);
insert into bill_author (billno, empid) values (39, 95);
insert into bill_author (billno, empid) values (59, 99);
insert into bill_author (billno, empid) values (1, 72);
insert into bill_author (billno, empid) values (87, 96);
insert into bill_author (billno, empid) values (86, 75);
insert into bill_author (billno, empid) values (32, 100);
insert into bill_author (billno, empid) values (74, 63);
insert into bill_author (billno, empid) values (73, 6);
insert into bill_author (billno, empid) values (63, 30);
insert into bill_author (billno, empid) values (36, 55);
insert into bill_author (billno, empid) values (50, 96);
insert into bill_author (billno, empid) values (3, 10);
insert into bill_author (billno, empid) values (37, 54);
insert into bill_author (billno, empid) values (97, 81);
insert into bill_author (billno, empid) values (31, 36);
insert into bill_author (billno, empid) values (84, 26);
insert into bill_author (billno, empid) values (68, 62);
insert into bill_author (billno, empid) values (68, 86);
insert into bill_author (billno, empid) values (65, 25);
insert into bill_author (billno, empid) values (20, 32);
insert into bill_author (billno, empid) values (23, 32);
insert into bill_author (billno, empid) values (47, 10);
insert into bill_author (billno, empid) values (74, 59);
insert into bill_author (billno, empid) values (14, 31);
insert into bill_author (billno, empid) values (36, 4);
insert into bill_author (billno, empid) values (97, 72);
insert into bill_author (billno, empid) values (6, 44);
insert into bill_author (billno, empid) values (2, 26);
insert into bill_author (billno, empid) values (32, 96);
insert into bill_author (billno, empid) values (38, 84);
insert into bill_author (billno, empid) values (12, 86);
insert into bill_author (billno, empid) values (74, 35);
insert into bill_author (billno, empid) values (94, 78);
insert into bill_author (billno, empid) values (86, 25);
insert into bill_author (billno, empid) values (54, 86);
insert into bill_author (billno, empid) values (31, 5);
insert into bill_author (billno, empid) values (55, 91);
insert into bill_author (billno, empid) values (26, 12);
insert into bill_author (billno, empid) values (88, 25);
insert into bill_author (billno, empid) values (14, 77);
insert into bill_author (billno, empid) values (63, 95);
insert into bill_author (billno, empid) values (73, 67);
insert into bill_author (billno, empid) values (99, 29);
insert into bill_author (billno, empid) values (46, 15);
insert into bill_author (billno, empid) values (74, 86);
insert into bill_author (billno, empid) values (36, 82);
insert into bill_author (billno, empid) values (25, 76);
insert into bill_author (billno, empid) values (88, 10);
insert into bill_author (billno, empid) values (1, 29);
insert into bill_author (billno, empid) values (4, 59);
insert into bill_author (billno, empid) values (31, 23);
insert into bill_author (billno, empid) values (81, 68);
insert into bill_author (billno, empid) values (61, 64);
insert into bill_author (billno, empid) values (9, 29);
insert into bill_author (billno, empid) values (7, 19);
insert into bill_author (billno, empid) values (97, 47);
insert into bill_author (billno, empid) values (97, 44);
insert into bill_author (billno, empid) values (6, 90);
insert into bill_author (billno, empid) values (22, 18);
insert into bill_author (billno, empid) values (64, 90);
insert into bill_author (billno, empid) values (52, 77);
insert into bill_author (billno, empid) values (77, 59);
insert into bill_author (billno, empid) values (70, 29);
insert into bill_author (billno, empid) values (6, 74);
insert into bill_author (billno, empid) values (55, 26);
insert into bill_author (billno, empid) values (93, 66);
insert into bill_author (billno, empid) values (97, 57);
insert into bill_author (billno, empid) values (17, 43);
insert into bill_author (billno, empid) values (64, 24);
insert into bill_author (billno, empid) values (60, 19);
insert into bill_author (billno, empid) values (34, 29);
insert into bill_author (billno, empid) values (42, 5);
insert into bill_author (billno, empid) values (33, 35);
insert into bill_author (billno, empid) values (5, 54);

insert into bill_subject (billno, subject) values (55, 'subject');
insert into bill_subject (billno, subject) values (80, 'cmsc127');
insert into bill_subject (billno, subject) values (88, 'cmsc124');
insert into bill_subject (billno, subject) values (74, 'ganda ni mam kat');
insert into bill_subject (billno, subject) values (48, 'cmsc100');
insert into bill_subject (billno, subject) values (21, 'cmsc131');
insert into bill_subject (billno, subject) values (2, 'sin tax on banana');
insert into bill_subject (billno, subject) values (12, 'node js illegalization');
insert into bill_subject (billno, subject) values (28, 'marijuana legalized');
insert into bill_subject (billno, subject) values (67, 'excise tax on pork');
insert into bill_subject (billno, subject) values (8, 'tax exemption');
insert into bill_subject (billno, subject) values (19, 'academic excellence');
insert into bill_subject (billno, subject) values (100, 'science progression');
insert into bill_subject (billno, subject) values (49, 'human rights');
insert into bill_subject (billno, subject) values (77, 'health');
insert into bill_subject (billno, subject) values (13, 'economy');
insert into bill_subject (billno, subject) values (31, 'phlo1');
insert into bill_subject (billno, subject) values (26, 'depression deletion');
insert into bill_subject (billno, subject) values (65, 'anxiety');
insert into bill_subject (billno, subject) values (14, 'stress');
insert into bill_subject (billno, subject) values (24, 'caffeine tax');
insert into bill_subject (billno, subject) values (60, 'mental health');
insert into bill_subject (billno, subject) values (71, 'reproductive');
insert into bill_subject (billno, subject) values (74, 'sustenance');
insert into bill_subject (billno, subject) values (36, 'housing');
insert into bill_subject (billno, subject) values (91, 'money subsidy');
insert into bill_subject (billno, subject) values (54, 'jobs');
insert into bill_subject (billno, subject) values (26, 'luv you maam');
insert into bill_subject (billno, subject) values (6, 'ipasa mo kami');
insert into bill_subject (billno, subject) values (77, 'ni dannah');
insert into bill_subject (billno, subject) values (50, 'lorem');
insert into bill_subject (billno, subject) values (86, 'ipsum');
insert into bill_subject (billno, subject) values (40, 'dolor';
insert into bill_subject (billno, subject) values (71, 'sit doggo');
insert into bill_subject (billno, subject) values (12, 'amet');
insert into bill_subject (billno, subject) values (62, 'much creative');
insert into bill_subject (billno, subject) values (14, 'very subject');
insert into bill_subject (billno, subject) values (77, 'wowable');
insert into bill_subject (billno, subject) values (49, 'chuchu');
insert into bill_subject (billno, subject) values (17, 'charaughter');
insert into bill_subject (billno, subject) values (93, 'this is sparta');
insert into bill_subject (billno, subject) values (39, 'war funds');
insert into bill_subject (billno, subject) values (36, 'soldier training');
insert into bill_subject (billno, subject) values (14, 'ROTC');
insert into bill_subject (billno, subject) values (97, 'sports');
insert into bill_subject (billno, subject) values (50, 'pork');
insert into bill_subject (billno, subject) values (40, 'drug eradication');
insert into bill_subject (billno, subject) values (100, 'construction');
insert into bill_subject (billno, subject) values (11, 'barely meaningful');
insert into bill_subject (billno, subject) values (36, 'hindi naman');
insert into bill_subject (billno, subject) values (21, 'ata kami nagquery ng');
insert into bill_subject (billno, subject) values (17, 'subjects');
insert into bill_subject (billno, subject) values (47, 'basic needs');
insert into bill_subject (billno, subject) values (30, 'free tuition');
insert into bill_subject (billno, subject) values (9, 'human rights');
insert into bill_subject (billno, subject) values (25, 'criminal rights');
insert into bill_subject (billno, subject) values (14, 'sustenance');
insert into bill_subject (billno, subject) values (79, 'subsidy');
insert into bill_subject (billno, subject) values (36, 'importation tax');
insert into bill_subject (billno, subject) values (26, 'tax exemption');
insert into bill_subject (billno, subject) values (80, 'pregnant women health');
insert into bill_subject (billno, subject) values (31, 'vaccination');
insert into bill_subject (billno, subject) values (38, 'realty');
insert into bill_subject (billno, subject) values (40, 'housing');
insert into bill_subject (billno, subject) values (41, 'college education');
insert into bill_subject (billno, subject) values (94, 'senior high school');
insert into bill_subject (billno, subject) values (97, 'exportation');
insert into bill_subject (billno, subject) values (67, 'importation');
insert into bill_subject (billno, subject) values (41, 'wildlife protection');
insert into bill_subject (billno, subject) values (12, 'preservation');
insert into bill_subject (billno, subject) values (98, 'mining regulations');
insert into bill_subject (billno, subject) values (49, 'watershed preservation');
insert into bill_subject (billno, subject) values (12, 'aesthetic');
insert into bill_subject (billno, subject) values (57, 'construction');
insert into bill_subject (billno, subject) values (29, 'MRT');
insert into bill_subject (billno, subject) values (52, 'transportation');
insert into bill_subject (billno, subject) values (49, 'infrastracture');
insert into bill_subject (billno, subject) values (95, 'building');
insert into bill_subject (billno, subject) values (9, 'dannah');
insert into bill_subject (billno, subject) values (5, 'louise');
insert into bill_subject (billno, subject) values (53, 'esperanza');
insert into bill_subject (billno, subject) values (10, 'kat');
insert into bill_subject (billno, subject) values (9, 'loren');
insert into bill_subject (billno, subject) values (55, 'tan');
insert into bill_subject (billno, subject) values (17, 'reggie');
insert into bill_subject (billno, subject) values (85, 'neil');
insert into bill_subject (billno, subject) values (23, 'recario');
insert into bill_subject (billno, subject) values (90, 'nepotism');
insert into bill_subject (billno, subject) values (15, 'anti-dynasty');
insert into bill_subject (billno, subject) values (57, 'lorem');
insert into bill_subject (billno, subject) values (92, 'integer');
insert into bill_subject (billno, subject) values (46, 'vide cor meum');
insert into bill_subject (billno, subject) values (86, "jeaux d'eaux");
insert into bill_subject (billno, subject) values (55, 'canon');
insert into bill_subject (billno, subject) values (53, 'chopin');
insert into bill_subject (billno, subject) values (15, 'randomization');
insert into bill_subject (billno, subject) values (75, 'abstraction');
insert into bill_subject (billno, subject) values (74, 'organ donations');
insert into bill_subject (billno, subject) values (8, 'real property');
insert into bill_subject (billno, subject) values (68, 'value-added tax ');
